export MODEL_NAME="runwayml/stable-diffusion-v1-5";
export OUTPUT_DIR="saved_models/custom_diffusion/single/dog6";
export INSTANCE_DIR="/data/twkim/diffusion/personalization/collected/images/dog6";
export CUDA_VISIBLE_DEVICES=6;
accelerate launch --main_process_port=9980 cd_train.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --train_data_dir1=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --resolution=512  \
  --train_batch_size=2  \
  --learning_rate=1e-5  \
  --lr_warmup_steps=0 \
  --max_train_steps=501 \
  --scale_lr  \
  --with_prior_preservation=1 \
  --prior_loss_weight=1.0 \
  --num_class_images=200 \
  --placeholder_token1="<dog6>" \
  --mask_tokens="[MASK]" \
  --cls_net_path="saved_models/mlm_models/mlm_contextnet_nonpad_lr1e4/checkpoints/cls_net_99000_ckpt.pt" \
  --mask_embed_path="saved_models/mlm_models/mlm_contextnet_nonpad_lr1e4/checkpoints/mask_embeds_99000_ckpt.pt" \
  --class_data_dir1=./priors/samples_dog/ \
  --lambda_mlm=0 \
  --class_prompt1="a picture of a dog" \
  --prior_concept1="dog" \
  --train_prompt_type="pet" \
  --run_name="tmp" \
  --mlm_target="masked" \
  --validation_steps=100 \
  --resume_path="saved_models/custom_diffusion/single/dog6/custom_nomlm_dog6/checkpoints/checkpoint-250" \
  --train_text_encoder=0 \
  --mask_prob=0

