export MODEL_NAME="runwayml/stable-diffusion-v1-5";
export OUTPUT_DIR="saved_models/custom_diffusion/single/pet_cat1";
export INSTANCE_DIR="/data/twkim/diffusion/personalization/collected/images/pet_cat1";
export CUDA_VISIBLE_DEVICES=0,1;
accelerate launch --main_process_port=9980 train_custom_diffusion_single_trunc.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --train_data_dir1=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --resolution=512  \
  --train_batch_size=2  \
  --learning_rate=1e-5  \
  --lr_warmup_steps=0 \
  --max_train_steps=251 \
  --scale_lr  \
  --with_prior_preservation=1 \
  --prior_loss_weight=1.0 \
  --num_class_images=200 \
  --placeholder_token1="<pet_cat1>" \
  --mask_tokens="[MASK]" \
  --cls_net_path="saved_models/mlm_models/mlm_contextnet_nonpad_lr1e4/checkpoints/cls_net_99000_ckpt.pt" \
  --mask_embed_path="saved_models/mlm_models/mlm_contextnet_nonpad_lr1e4/checkpoints/mask_embeds_99000_ckpt.pt" \
  --class_data_dir1=./priors/samples_cat/ \
  --lambda_mlm=0 \
  --class_prompt1="a picture of a cat" \
  --prior_concept1="cat" \
  --prompt_type="pet" \
  --run_name="tmp" \
  --mlm_target="masked" \
  --validation_steps=50 
